version: 2.1

jobs:
  run_ci:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y cmake ninja-build cpputest
      - run: cmake -B build/ -G Ninja
      - run: ninja -C build/
      - run: ninja -C build/ check_style
      - run: ninja -C build/ run_tests

workflows:
  say-hello-workflow:
    jobs:
      - run_ci
