#!/bin/sh

# This hook will look at the syntax of the commit message and check if it follows the conventional commit format
# If not, it will reject it
# For more information on the conventional commit format, refer to https://www.conventionalcommits.org/
# And for the commit types https://github.com/pvdlg/conventional-commit-types

if egrep -q "(feat|fix|improvement|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: .{1,50}" $1; then
	exit 0
else
	echo "Error: Commit message doesn't follow the conventional commit format, check the commit-msg hook for more information."
	exit 1
fi
